config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:show,:update, :edit, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :micropost
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :micropost_id, presence: true
  validates :content, presence: true, length: {maximum: 1000}
  before_update :set_time
  def set_time
  	self.time_edit = Time.zone.now
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :logged_in_user, only: [ :create, :destroy]
	before_action :correct_user, only: :destroy

	def create
		@micropost = Micropost.find(params[:comment][:micropost_id])
		@comment = @micropost.comments.build(comment_params)
		respond_to do |format|
      	if !@comment.save
        	flash[:alert] = "You can not comment"
    	 end
     	 format.html { redirect_to @micropost }
     	 format.js { @comments = @micropost.comments }
     	end

    end

	def edit
		@comment = Comment.find(params[:id])
		@micropost = @comment.micropost
		@user = @comment.user
		
	end
	def update
		@comment = Comment.find(params[:id])
		@micropost = @comment.micropost
		if !@comment.update(comment_params)
      	 	flash[:alert] = "Can not edit comment"
    	end
    	redirect_to @micropost
  	end

	def destroy
		@comment.destroy
		flash[:success] = "Comment deleted"
		redirect_to request.referrer 
	end

	private

	def comment_params
		params.require(:comment).permit(:content, :user_id)
	end
	def correct_user
		@comment = current_user.comments.find_by(id: params[:id])
		redirect_to root_url if @comment.nil?
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <%= link_to gravatar_for(comment.user, size: 50), comment.user %>
  <span class="content">
  <% if current_user == comment.user %>
      <li class="dropdown edit">
        <a href="#" class="dropdown-toggle edit-comment" data-toggle="dropdown">
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Edit...", edit_comment_path(comment) %></li>
          <li><%= link_to "Delete...", comment, method: :delete, data: { confirm: "You sure"} %></li>
        </ul>
      </li>
    <%end%>
  <%= comment.content %>
      </span>
  <span class="timestamp">Posted 
    <% unless comment.time_edit.nil?%>
      <%= time_ago_in_words(comment.time_edit) %> ago. Edited 
    <%else%>
      <%= time_ago_in_words(comment.created_at) %>
    <%end%>
    in <%= comment.created_at.strftime("%b %d, %Y") %> by
    <span class="user"><%= link_to comment.user.name, comment.user %></span>
    </span>
</li>

app/views/comments/create.js.erb
$("#comments").html("<%= escape_javascript(render @comments) %>");
$("#count").html("<%= @micropost.comments.count %>");
$("#new_comment")[0].reset();

app/views/comments/edit.html.erb
<div class="row">
<div class="col-md-2">
</div>
<div class="col-md-10">
<h1>Edit comment</h1>
<%= form_for(@comment) do |f| %>
  <div class="field">
  <%= render 'shared/error_messages', object: f.object %>
    <%= f.text_area :content, placeholder: "edit comment...", required: true %>
    <%= f.hidden_field :micropost_id,  value: @micropost.id %>
    <%= f.hidden_field :user_id, value: @user.id %>
  </div>
  <%= f.submit "Save change", class: "btn btn-primary" %>
<% end %>
</div>
</div>